### ISSUE TITLE
Providing AMP support

### ISSUE THREAD

**Issue by jwold** [jacklenox/susty#14]
At XWP our team has been working with the folks at Google on bringing AMP support to more WordPress themes. 

I'm really curious about a version of Susty that could provide [native AMP support](https://github.com/Automattic/amp-wp). I've been using Susty for the past few months, and loving it!

**Comment by iandunn** [comment]
I'm curious what the point of integrating AMP would be? Doesn't Susty already solve the problems that AMP is trying to solve, by its very nature? Perhaps I'm missing something about AMP that would be useful to a project like this?

**Comment by pbuzdin** [comment]
Amp is solved by plugin

**Comment by jacklenox** [comment]
Hi @jwold, thanks for the comment and apologies for the delay in replying here. I'm going to close this comment as I agree with the other comments above.
