### ISSUE TITLE
Thanks :)

### ISSUE THREAD

**Issue by lordspace** [jacklenox/susty#3]
This isn't a bug just wanted to say thanks for your effort. :)

**Comment by jacklenox** [comment]
Thank you very much @lordspace!

I shall take pleasure in marking this as a `wontfix`, and making it the first closed issue! :smile:

**Comment by lordspace** [comment]
Sounds good Jack :D
The only problem that I see when the site loads that fast is that I am very tempted to click on the links multiple times to make sure this is is happening.
