### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by cfoellmann** [jacklenox/susty#4]
Could tag to allow for faster fetching of the package via composer?

**Comment by jacklenox** [comment]
Sorry for the slow reply. Hmm, do people install themes with composer? I'll get this sorted anyway when I get a moment.

**Comment by cfoellmann** [comment]
Yes! me 😀

**Comment by khromov** [comment]
@jacklenox I added basic Composer support in https://github.com/jacklenox/susty/pull/8

If you upload the theme to the .org theme repo, it will also be possible to pull the theme in using https://wpackagist.org/

**Comment by jacklenox** [comment]
Thanks @khromov, it's merged. :+1:

**Comment by jacklenox** [comment]
This is effectively sorted now I think, so I'm closing this issue. Thanks all.
