### ISSUE TITLE
Minified style.css

### ISSUE THREAD

**Issue by cfoellmann** [jacklenox/susty#5]
wouldn't a minified style.css shave off some more bytes? 😁 

This is not common practice although I dont understand why.

**Comment by KasperAndersson** [comment]
@cfoellmann Just compress the CSS and HTML on your server (gzip or broccoli).

**Comment by jacklenox** [comment]
@cfoellmann Sorry for the delay here. As this repo contains the source code of the theme, I've opted not to minify the CSS. It's fairly common practice to not include minified or compiled code in public repos.

Of course, I do minify the CSS in production, as everyone should. :smile:

**Comment by cfoellmann** [comment]
@jacklenox no problem.
